export const GameStates = {
    INIT: 'INIT',
    LOADING: 'LOADING',
    LOBBY: 'LOBBY',
    DEAL: 'DEAL',
    REVIEW: 'REVIEW',
    DISCUSS: 'DISCUSS',
    MITIGATION: 'MITIGATION',
    JUDGMENT_CALL: 'JUDGMENT CALL',
    OUTPUT: 'OUTPUT'
}