export const SocketStates = {
    CONNECTION: 'connection',
    /** Lobby Sockets States  */
    // Lobby Connection
    CONNECT_TO_LOBBY: 'CONNECT TO LOBBY',
    // Requested Events
    NEED_LOBBY_CODE: 'NEED LOBBY CODE',
    CLIENT_DISCONNECT: 'disconnect',
    CLIENT_JOINED_LOBBY: 'CLIENT JOINED LOBBY',
    REQUESTING_LOBBY_INFO: 'REQUESTING LOBBY INFO',
    UPDATE_READY_STATE: 'UPDATE PLAYER READY STATE',
    DOES_LOBBY_EXIST: 'DOES LOBBY EXIST',

    // Response Events
    CLIENT_CONNECTED: 'CLIENT CONNECTED',
    FOUND_LOBBY_CODE: 'FOUND LOBBY CODE',
    WELCOME_PLAYER: 'WELCOME PLAYER',
    SENDING_LOBBY_INFO:  'SENDING LOBBY INFO',
    REFRESH_PLAYER_LIST: 'REFRESH PLAYER LIST',
    CONFIRM_UPDATE_READY_STATE:  'CONFIRMED PLAYER READY STATE',
    LOBBY_EXIST_RESPONSE: 'LOBBY EXISTENCE RESPONSE',

    /** Game Socket States */
    // Requested Events
    DEAL_GAME_READY: 'DEAL - GAME READY',
    REVIEW_GAME_READY: 'REVOEW - GAME READY',
    DISCUSS_GAME_READY: 'DISCUSS - GAME READY',
    MITIGATION_GAME_READY: ' MITIGATION - GAME READY',
    JUDGMENT_CALL_GAME_READY: 'JUDGMENT CALL - GAME READY',

    // Response Events
    INIT_PLAYERS_READY: 'INIT - ALL PLAYERS READY.',

    // Deal
    DEAL_INIT: 'DEAL - INIT',

    // Review
    REVIEW_INIT: 'REVIEW - INIT',
    REVIEW_ROUND_OVER: 'REVIEW - ROUND OVER',

    // DISCUSS
    DISCUSS_INIT: 'DISCUSS - INIT',
    DISCUSS_ROUND_OVER: 'DISCUSS - ROUND OVER',

    // MITIGATION
    MITIGATION_INIT: 'MITIGATION - INIT',
    MITIGATION_ROUND_OVER: 'MITIGATION - ROUND OVER',

    // JUDGMENT CALL
    JUDGMENT_CALL_INIT: 'JUDGMENT CALL - INIT',
    JUDGMENT_CALL_ROUND_OVER: 'JUDGMENT CALL - ROUND OVER',

    // ENDGAME
    ENDGAME_OUTPUT: 'ENDGAME - OUTPUT'
    

}